using System.Text;

namespace Recon.Delink;

/// <summary>
/// The linker script that puts every section back at the address it came from. Addresses in a PE
/// linker script are absolute virtual addresses, not RVAs, so each one is the image base plus the
/// section's RVA — which is also why the plan records the image base it was written for.
/// </summary>
public static class LinkerScriptWriter
{
    public static string Emit(DelinkDocument plan)
    {
        var body = new StringBuilder();
        body.Append("/* generated by recon delink ").Append(DelinkSchema.Version).Append(" - do not edit */\n");
        body.Append("SECTIONS\n{\n");

        foreach (var section in plan.Sections.Where(s => s.Emitted).OrderBy(s => s.Rva))
        {
            body.Append("  . = 0x").Append((plan.Binary.ImageBase + section.Rva).ToString("x")).Append(";\n");
            string name = section.Output ?? AsmWriter.SectionName(section.Name);
            string input = section.Input ?? AsmWriter.InputSectionName(name);

            // A section with a zero-filled tail gets the uninitialised block that carries it: with a
            // script, sections are placed by name, so the block has to be named as this section's.
            string tail = section.TailBytes > 0 ? " *(.bss)" : string.Empty;
            body.Append("  ").Append(name).Append(" : { *(").Append(input).Append(')').Append(tail).Append(" }\n");
        }

        // Addresses nothing names, so that a reference to one has something to point at.
        var synthetic = plan.Symbols.Where(s => s.Synthetic).OrderBy(s => s.Rva).ToList();
        if (synthetic.Count > 0)
        {
            body.Append('\n');
            body.Append("  /* addresses with no name of their own */\n");
            foreach (var symbol in synthetic)
            {
                body.Append("  ").Append(symbol.Name).Append(" = 0x")
                    .Append((plan.Binary.ImageBase + symbol.Rva).ToString("x")).Append(";\n");
            }
        }

        // The assembler writes debug sections of its own as it assembles our files — a .debug_line
        // for the file it is assembling, for example. Nothing asked for them and they are not part of
        // the image, so they are thrown away rather than left for the linker to find a home for.
        body.Append('\n');
        body.Append("  /* sections the assembler writes for itself */\n");
        body.Append("  /DISCARD/ :\n  {\n");
        foreach (string name in AsmWriter.AssemblerOwnPatterns())
        {
            body.Append("    *(").Append(name).Append(")\n");
        }

        body.Append("  }\n");
        body.Append("}\n");
        return body.ToString();
    }
}
