using System.Text;

namespace Recon.Cli;

public static class Help
{
    public static void Print(TextWriter writer, string? command = null)
    {
        if (command is not null)
        {
            var spec = CommandSpecs.Find(command);
            if (spec is not null)
            {
                writer.WriteLine($"usage: {spec.Usage}");
                writer.WriteLine();
                writer.WriteLine(spec.Summary);
                if (spec.Options.Length > 0)
                {
                    writer.WriteLine();
                    writer.WriteLine("options:");
                    foreach (var option in spec.Options)
                    {
                        writer.WriteLine($"  {option}");
                    }
                }

                return;
            }
        }

        writer.WriteLine($"{EntryPoint.ToolName} {EntryPoint.Version} - reversing and reconstruction toolkit");
        writer.WriteLine();
        writer.WriteLine($"usage: {EntryPoint.ToolName} <command> [options]");
        writer.WriteLine();
        writer.WriteLine("commands:");
        foreach (var spec in CommandSpecs.All)
        {
            writer.WriteLine($"  {spec.Name,-11} {spec.Summary}");
        }

        writer.WriteLine();
        writer.WriteLine("global options:");
        writer.WriteLine("  --project <dir|file>   project to work on (default: search upward from the current directory)");
        writer.WriteLine("  --json                 machine-readable output on stdout");
        writer.WriteLine("  --verbose              extra progress on stderr");
        writer.WriteLine("  --quiet                suppress human-readable output");
        writer.WriteLine("  --version              print the version");
        writer.WriteLine("  --help [command]       this text, or help for one command");
        writer.WriteLine();
        writer.WriteLine("exit codes: 0 ok, 1 check failed, 2 usage error, 3 configuration error, 4 internal error");
    }

    /// <summary>Generates the command reference from the same table <c>--help</c> uses.</summary>
    public static string GenerateMarkdown()
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Command reference");
        builder.AppendLine();
        builder.AppendLine("<!-- Generated by `recon gen-docs`. Do not edit by hand. -->");
        builder.AppendLine();
        builder.AppendLine($"Tool version: {EntryPoint.Version}");
        builder.AppendLine();
        builder.AppendLine("Global options: `--project <dir|file>`, `--json`, `--verbose`, `--quiet`, `--version`, `--help`.");
        builder.AppendLine();
        builder.AppendLine("Exit codes: `0` ok, `1` a check failed, `2` usage error, `3` configuration error, `4` internal error.");
        builder.AppendLine();

        foreach (var spec in CommandSpecs.All)
        {
            builder.AppendLine($"## `{spec.Name}`");
            builder.AppendLine();
            builder.AppendLine("```");
            builder.AppendLine(spec.Usage);
            builder.AppendLine("```");
            builder.AppendLine();
            builder.AppendLine(spec.Summary);
            builder.AppendLine();
            if (spec.Options.Length > 0)
            {
                builder.AppendLine("| option | meaning |");
                builder.AppendLine("| --- | --- |");
                foreach (var option in spec.Options)
                {
                    builder.AppendLine($"| `{option}` | see `--help` for details |");
                }

                builder.AppendLine();
            }
        }

        return builder.ToString();
    }
}
